[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
lib_deps =
  https://github.com/sparkfun/SparkFun_6DoF_ISM330DHCX_Arduino_Library.git
build_src_filter =
  +<*>
  -<uploadcheck_blink.cpp>
build_flags =
  -D USB_SERIAL
  -I"$PROJECT_DIR/.pio-core/packages/toolchain-gccarmnoneeabi-teensy/arm-none-eabi/include/c++/11.3.1/arm-none-eabi"

[env:teensy41_uploadcheck]
extends = env:teensy41
lib_deps =
build_src_filter =
  -<*>
  +<uploadcheck_blink.cpp>

[env:teensy41_validation]
extends = env:teensy41
lib_deps =
lib_extra_dirs =
  .pio/libdeps/teensy41
build_flags =
  ${env:teensy41.build_flags}
  -D LOGGER_VALIDATION_AUTORUN=1
  -D LOGGER_VALIDATION_DURATION_MS=200
